# Generated by Django 3.1.2 on 2020-10-27 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('authors', models.CharField(max_length=2048)),
                ('year', models.PositiveIntegerField()),
                ('journal', models.CharField(max_length=256)),
                ('volume', models.IntegerField(blank=True)),
                ('number', models.IntegerField(blank=True)),
                ('doi', models.CharField(blank=True, max_length=128)),
                ('url', models.URLField(blank=True)),
            ],
        ),
    ]
